### PR TITLE
todo-to-issues: Comment TODO so it won't be visible in output

### PR DESCRIPTION
**Pull request by patrickbenkoetter**
Commented a TODO to hide it in rendered output

### CODE REVIEW

**Comment by cstrotm** [comment]
Should we go through all documents, search for TODOs and convert them into github issues?

**Comment by patrickbenkoetter** [comment]
* Carsten Strotmann <reply@reply.github.com>:
> Should we go through all documents, search for TODOs and convert them into github issues?

We're almost done with it. ;-)

p@rick

-- 
[*] sys4 AG
 
https://sys4.de, +49 (89) 30 90 46 64
Schleißheimer Straße 26/MG,80333 München
 
Sitz der Gesellschaft: München, Amtsgericht München: HRB 199263
Vorstand: Patrick Ben Koetter, Marc Schiffbauer, Wolfgang Stief
Aufsichtsratsvorsitzender: Florian Kirstein

**Review by hartwork — COMMENTED** [review]
I see line-wrapping changes here, only. No objections, but I don't see a match to title `todo-to-issues: Comment TODO so it won't be visible in output`, content-wise. How do we move forward?

**Comment by sebix** [comment]
I am also confused about the mismatch between the PR title and the actual proposed change

**Pull request closed without merging**
