### PR TITLE
Add HAProxy configuration

### PR DESCRIPTION
**Pull request by schue30**

### CODE REVIEW

**Comment by azet** [comment]
this looks good to me.

what about session-cache and timeout? how are session tickets and resumption handled by haproxy? session tickets should be enabled if they cannot be rotated on-line.

**Comment by schue30** [comment]
OCSP stapling and HPKP are now mentioned as additional settings.
Session tickets are now disabled in the default configration.

**Comment by azet** [comment]
Excellent addition, thank you!

**Comment by azet** [comment]
Fixed spelling mistake (stapling vs. stampling) in a follow up commit (c85b61b76d95bddc193b5886bb3827c009cd2847).

**Pull request merged**
