### PR TITLE
gitignore: ignore tempoary files *~

### PR DESCRIPTION
**Pull request by sebix**

### CODE REVIEW

**Comment by ignisf** [comment]
I don't believe that `.gitignore` should be used to work around a misconfigured editor.

**Comment by norpol** [comment]
I think the gitignore should also include temp files of some peoples editors. I think I'm not alone with that opinion, if I remember correctly I've "even" read on some git book in the past. gitignore can be bloated, imo (as long as it does not accidental ignore files that should not be ignored). Alternatively @sebix could use `set backupdir=$TEMP//` is his vim configuration, but I personally prefer to have tmp files in the folder I'm working in right now.
</senf>

**Comment by sebix** [comment]
I haven't thought that this small change attracts 2 comments to fast, while my other three PRs have got no comments so far. Please focus on more important parts of this doc. Discussions about *misconfigured editors* won't bring us forward.

For some it may be a misconfiguration, for others it's a convenience. In either case it's a very practical change adding compatibility and reducing efforts.

**Comment by azet** [comment]
trivial.

**Pull request merged**
