### PR TITLE
Cisco ESA/IronPort subsection

### PR DESCRIPTION
**Pull request by 2001db8**
Added a section for Cisco ESA (formerly known as IronPort) mail appliances. 

Almost everything can be configured either via CLI or WEBUI but CLI configuration is often more complex and requires several sub-commands so I stuck to WEBUI where possible in order to keep it simple and short.

Regards,
Jens

### CODE REVIEW

**Comment by azet** [comment]
@2001db8 

This looks like a good addition. Unfortunately I have no way to test this amid missing hardware. Would you be willing to bring this PR up on the mailing-list [0] as well to see if other people can give some feedback?

[0] - https://lists.cert.at/cgi-bin/mailman/listinfo/ach

**Comment by 2001db8** [comment]
I've added some screenshots of the UI configuration steps.

Regards
Jens

**Comment by azet** [comment]
@2001db8 

Cool. Thanks. Still waiting for people who can at least take a second look at this.

**Comment by krautsourced** [comment]
Looks good to me, if that means anything...

**Comment by fstern** [comment]
Looks also good from my side.

**Pull request merged**
