### PR TITLE
[work in progress] begin rst conversion

### PR DESCRIPTION
**Pull request by krono**
Please do not merge yet, but comment :)

### CODE REVIEW

**Comment by azet** [comment]
@krono 

Can you bring this PR up on the mailing list? We'd need reviewers for it. I haven't seen any additions since you initially opened this issue. If we take this on, I'd also suggest we keep a separate branch for the existing LaTeX document and the "2.0"-change: ReStructuredText, which we've been talking about in the past.

**Comment by krono** [comment]
I'll do in due time.

**Comment by sebix** [comment]
@krono What is the status? Is there something missing? How did you convert it? 

I know that it is out of date, but the changes since then are not so big.

**Comment by krono** [comment]
* Status is dormant.
* Have not looked at it since about 10 Month.
* Convert: initially pandoc, rest manually.

I have currently no time at all for that, life things and such…

**Comment by sebix** [comment]
Are all files converted and did you stop with the manual fixes or did you stop within both automatic and manual conversion?

**Comment by krono** [comment]
I cannot remember completely. But I did _one_ conversion step, looked at it and then started changing stuff. I wouldn't go forward with automatic conversion. The LaTeX grew too complex for that already.

**Comment by krono** [comment]
(but thanks for keeping things up!)

**Comment by krono** [comment]
We are outdated now. Sorry.

**Pull request closed without merging**
