### PR TITLE
remove $host variable, add some tested versions

### PR DESCRIPTION
**Pull request by FireFart**
Some changes:

* Added new tested versions
* Don't use the `$host` variable in NGINX it's the user controlled host header

Sorry for the Whitespace changes, my editor deletes them automatically on save. I think it has no impact to the document's style

### CODE REVIEW

**Comment by sebix** [comment]
@FireFart  Can you bring this topic up on the mailing list please? We would also have to change this for the other webservers too and we need a explanation for that in the guide.

**Comment by FireFart** [comment]
@sebix done

**Comment by azet** [comment]
Please don't open PRs on commits named 'some changes' - be a bit more declarative :)

**Comment by FireFart** [comment]
@azet changed :)

**Pull request merged**
