### PR TITLE
Dovecot: added options of newer Versions

### PR DESCRIPTION
**Pull request by gunnarhaslinger**
Dovecot: 
+ ssl_dh_parameters_length
+ ssl_prefer_server_ciphers
+ ssl_options=no_compression
+ Test with SSLyze

### CODE REVIEW

**Comment by krono** [comment]
Looks good from here.

Note that we should split config files if they differ too much from version to version

**Comment by sebix** [comment]
+1

**Comment by azet** [comment]
I'd usually say yes but in the case of e-mail I'm unsure that disabling SSLv3 is a good idea. We recently did a study on SSL/TLS usage in e-mail related protocols [0]. TLS 1.0 is most widely supported, but SSLv3 is at a close second. So if you disable SSLv3 the fallback will be plaintext. Most HTTP(S) attacks also won't work on e-mail related protocols.


[0] https://www.slideshare.net/a_z_e_t/no-need-for-black-chamers-testing-tls-in-the-email-ecosystem-at-large

**Comment by gunnarhaslinger** [comment]
I didn't change the Bettercrypto recommendation in that point - its the same as before, recommended disabling SSLv2 and SSLv3 for Dovecot.
AND: I dont't think there are MUA out there which still require SSLv3 and are not capable of doing at least TLSv1. 
Your Input that you knock out the Mailsystem by disabling SSL is true for SMTP, but this is MTA to MTA communication with Plaintext-Fallback. But Dovecot is only good for MUA Connections, and every Smartphone and/or Windows/MAC/Linux-Mailclient is capable of doing POP3/IMAP via TLS.

**Comment by sebix** [comment]
@azet We are talking about clients, so the server survey is not relevant here IMHO. We expect that clients should be able to talk TLS in the HTTP case, so why not for IMAP/POP3?

Is there a paper with more detailed information on the survey? Haven't found it one at sba website.

**Comment by azet** [comment]
Paper isn't public yet. Numbers for IMAP/POP3 are better and a move away from SSLv3 is more warranted. But there's still support for it, so not sure we should entirely exclude it? Hmmm.

**Comment by gunnarhaslinger** [comment]
As I already said: I didn't change this setting, just modified the Comment-Line. I'm not aware of Devices still using SSLv3 for IMAPS/POP3S, and all Software for Windows/Linux/Mac which is maybe affected should be updated.

**Comment by azet** [comment]
> As I already said: I didn't change this setting, just modified the Comment-Line. I'm not aware of Devices still using SSLv3 for IMAPS/POP3S, and all Software for Windows/Linux/Mac which is maybe affected should be updated.

see this slide: http://www.slideshare.net/a_z_e_t/no-need-for-black-chamers-testing-tls-in-the-email-ecosystem-at-large#17

**Comment by sebix** [comment]
And why is this relevant? > 95% of IMAP/POP3 server support TLSv1.0. Great! We don't have any recommendations for server software not supporting TLS (implicit rec.: upgrade)

Your survey says nothing about client support, but that's the only relevant point here, as this setting's impacts on the client-to-server connections.

**Comment by azet** [comment]
Guess you're right there. So most dovecot instances will support TLS1.0 and above.

**Comment by gunnarhaslinger** [comment]
BetterCrypto Guide - Postfix recommendation. There is only TLS and no SSL for the Submission-Port in the docs. Argument is: For the MSA smtpd process which communicates with mail clients, we first define the ciphers that are acceptable for the “mandatory” security level => and mandatory Security level is typical bettercrypto cipher-suite. If you think there are User-Devices out there which are not capable using these ciphers and TLS even all MTA-Recommendations on the Submission-Port have to be changed. 
For me the Recommendation to disable SSL for Submission-Port and MUA-Ports is ok and practicable. MTA-to-MTA Communication is an other topic because of the Plaintext-Fallback in SMTP, and weak crypto is even better than no crypto.

**Comment by aaronkaplan** [comment]
> On 27 Oct 2015, at 14:51, Gunnar Haslinger <notifications@github.com> wrote:
> 
> BetterCrypto Guide - Postfix recommendation. There is only TLS and no SSL for the Submission-Port in the docs. Argument is: For the MSA smtpd process which communicates with mail clients, we first define the ciphers that are acceptable for the “mandatory” security level => and mandatory Security level is typical bettercrypto cipher-suite. If you think there are User-Devices out there which are not capable using these ciphers and TLS even all MTA-Recommendations on the Submission-Port have to be changed.
> For me the Recommendation to disable SSL for Submission-Port and MUA-Ports is ok and practicable. MTA-to-MTA Communication is an other topic because of the Plaintext-Fallback in SMTP, and weak crypto is even better than no crypto.
> 

I agree here.
The general understanding while writing the bulk of the document was: MTA-to-MTA case: use whatever crypto is available (any is better than none).
For all other cases: use reasonable settings. If it’s a compatibility issue - you can weaken it if you must, but it’s not the better crypto recommendation. After all it is called "better crypto”.

Best,
a.

**Comment by sebix** [comment]
As there are no objections anymore, anyone willing to merge it? @aaronkaplan @azet

**Comment by azet** [comment]
Yep. BTW I've granted you permissions to do so as well.

**Pull request merged**
