### PR TITLE
Add information about Pollinate and entropy.ubuntu.com service.

### PR DESCRIPTION
**Pull request by burghardt**

### CODE REVIEW

**Comment by bashrc** [comment]
"Entropy as a service" seems like a spectacularly bad idea. Think about it from the point of view of an adversary.

> "or clear text HTTP connections..."

**Comment by burghardt** [comment]
Clear-text HTTP support is there for pulling entropy from local services. Imagine virtual machines on physical machine. Each of them san securely obtain PRNG seed over host-only interface with non-TLS HTTP. This also address problem with creation of TLS session while little or no entropy is available. I.e. generation of SSH keys on first boot will hung if operating system is unable to gather enough entropy. Pollinate prevent this.

More on Pollinate:
* http://blog.dustinkirkland.com/2014/02/random-seeds-in-ubuntu-1404-lts-cloud.html

Criticism:
* https://plus.google.com/+LennartPoetteringTheOneAndOnly/posts/K22yyHRc6hn 
* https://tim.siosm.fr/blog/2014/04/25/why-not-ubuntu-14.04-lts/#pollinate

**Comment by azet** [comment]
I'm also quite unsure if we should advertise pollinate etc. - these tools were developed for very specific environments, some lack proper documentation and haven't been audited. If a large scale cluster decides to use them, it's up to their tech. staff to decide about pro's and con's w.r.t. deployment of such tools.

I'd be *really* uncomfortable putting these in our guide right now. Canonical also tends to be very bad in coding/security practices and upkeep of some of their projects. So I'm clearly against this right now.

**Comment by azet** [comment]
BTW: apart from that -- newer linux kernel versions (4+) deal with VMs, entropy differently and have a new urandom construction than they used to a few years back when pollinate was first introduced.

**Comment by azet** [comment]
Closing due to inactivity. Please discuss this on-list: https://lists.cert.at/cgi-bin/mailman/listinfo/ach

**Pull request closed without merging**
