### PR TITLE
Update Configuration for Cisco ASA

### PR DESCRIPTION
**Pull request by roock**
The referenced version 9.1 is already rather old and some commands have been depreciated and/or changed.

### CODE REVIEW

**Comment by sebix** [comment]
Would it be possible to keep the settings for 9.1 while also adding the 9.8 recommendations?

**Review by azet — APPROVED** [review]
I work a lot with ASA and Firepower. These changes reflect BCP on Cisco ASA (soon to be end of life/support, already end of sale for most ASA series). Reviewed and approved.

**Comment by sebix** [comment]
@azet Would it be worth to keep the section for Cisco ASA 9.1? Otherwise I'm OK with the PR - I can't check the content, but you've done that already.

**Comment by azet** [comment]
Yes - Cisco ASA is still widely in use today and the syntax didn't change so far between recent versions. I don't expect it to change anymore either; These appliances are end of sale but get support for a longer time because of their wide deployment and the Cisco Firepower series - which is supposed to replace ASA - still lacking in many places, being buggy and much more complicated to debug from my experience. I see many companies even switching vendors due to the lacking quality of the Firepower series, although it's improved over the past two years. I expect ASAs being around for quite a while still, especially as site to site VPN appliances/concentrators as well as AnyConnect end points (Cisco's remote access VPN software with extensive integration into third party software and operating systems. AnyConnect has been reasonably implemented into the new Firepower series though)

Short note in Firepower; many legacy features like Firewalling and Routing come from a ASA layer (called "LINA") that runs like a program in Firepower appliances - it's indirectly configured via the new Web UI or centralized management. The config/"show run" syntax is identical. Features like IDS run on other layers ie the underlying Linux system.

**Review by sebix — APPROVED** [review]

**Pull request merged**
